export interface MenuItem {
  name: string;
  description: string;
  price: string;
  badge: string | null;
  image: string | null;
  objectPosition?: string;
  components?: string[];
  timeSlot?: string;
}

export interface MenuCategory {
  category: string;
  items: MenuItem[];
}

export const menu: MenuCategory[] = [
  {
    category: "Signatures",
    items: [
      {
        name: "Brunch Signature 86",
        description: "Création salée + dessert signature + limonade maison — formule complète (10h–15h)",
        price: "25",
        badge: "Formule",
        image: null,
        components: ["Création salée", "Dessert signature", "Limonade maison"],
        timeSlot: "10h – 15h",
      },
      {
        name: "Sweet Chicken Waffle",
        description: "Gaufre de Bruxelles, poulet caramélisé, crudités, oignons crispy, crumble de cacahuètes & sirop d'érable · +oeuf +3 · +avocat +3",
        price: "14",
        badge: "Best Seller",
        image: "IMG_3256 19.15.09.jpg",
        objectPosition: "center",
      },
      {
        name: "Burrata Crush",
        description: "Pain complet, burrata crémeuse, pesto, tomates cerises, roquette fraîche",
        price: "14",
        badge: null,
        image: "IMG_3455.jpg",
        objectPosition: "center 70%",
      },
      {
        name: "Cheesy Toast",
        description: "Pain toasté, fromages fondants, tomate, pesto & huile d'olive citronnée · +oeuf +3 · +poulet +4",
        price: "13",
        badge: null,
        image: "A7400119 18.44.33.jpg",
        objectPosition: "center 60%",
      },
    ],
  },
  {
    category: "Brunch Salé",
    items: [
      {
        name: "Salmon Brunch Pancakes",
        description: "Pancakes, saumon fumé, guacamole crémeux, pousses fraîches & herbes · +oeuf +3 · +saumon +4",
        price: "15",
        badge: null,
        image: "A7403214.jpg",
        objectPosition: "center bottom",
      },
      {
        name: "Msemen Nomade",
        description: "Msemen grillé, feta, tomates cerises & séchées, roquette, noix & filet de miel",
        price: "13",
        badge: null,
        image: "A7406821.jpg",
        objectPosition: "center 65%",
      },
      {
        name: "Pure Green",
        description: "Pain sans gluten, avocat, pousses fraîches, crudités & huile d'olive citronnée · +oeuf +3 · +saumon +4",
        price: "13",
        badge: "GF · DF",
        image: "IMG_3465.jpg",
        objectPosition: "center bottom",
      },
      {
        name: "Avocado Eggs Toast",
        description: "Pain complet, crème d'avocat citronnée, oeuf, pousses fraîches, graines torréfiées & huile d'olive · +saumon +4 · +feta +2",
        price: "13",
        badge: null,
        image: "A7403418.jpg",
        objectPosition: "center bottom",
      },
    ],
  },
  {
    category: "Pains Rustiques",
    items: [
      {
        name: "Chicken Tartare",
        description: "Poulet, sauce tartare, tomates, oignons, salade et crudités · 9 avec 1 soft",
        price: "7",
        badge: null,
        image: "A7403512.jpg",
        objectPosition: "center 70%",
      },
      {
        name: "Burrata & Pesto Verde",
        description: "Burrata, tomates, roquette, oignons rouge, pesto · 9 avec 1 soft",
        price: "7",
        badge: null,
        image: "A7403502.jpg",
        objectPosition: "center 65%",
      },
      {
        name: "Fresh Saumon",
        description: "Saumon, fromage frais, herbes fraîches et crudités · 9 avec 1 soft",
        price: "7",
        badge: null,
        image: "A7403492.jpg",
        objectPosition: "center 65%",
      },
    ],
  },
  {
    category: "Douceurs",
    items: [
      {
        name: "L'Envolée Pistache",
        description: "Pancakes, coulant pistache & fruits de saison",
        price: "13",
        badge: null,
        image: null,
      },
      {
        name: "La Tentation aux Fruits Rouges",
        description: "Pancakes fruits de saison & coulis intense fruits rouges · +boule de glace +2",
        price: "12",
        badge: null,
        image: "A7403289.jpg",
        objectPosition: "center bottom",
      },
      {
        name: "Peanut Caramel",
        description: "Pancakes caramel beurre salé, bananes & cacahuètes torréfiées · +boule de glace +2",
        price: "12",
        badge: null,
        image: "A7403335.jpg",
        objectPosition: "center bottom",
      },
      {
        name: "Inspiration Tiramisu",
        description: "Pancakes, crème mascarpone, cacao & café",
        price: "12",
        badge: null,
        image: "A7400505.jpg",
      },
      {
        name: "Pain Perdu Signature 86",
        description: "Pain sans gluten doré, fruits de saison, sirop d'érable & yaourt végétal",
        price: "13",
        badge: "GF · DF",
        image: "IMG_3530 19.15.09.jpg",
      },
      {
        name: "Gaufres de Liège",
        description: "Gaufre liégeoise · +coulis +2 · +crème fouettée +2 · +fruits frais +3 · +glace +2",
        price: "5",
        badge: null,
        image: "A7403397.jpg",
      },
      {
        name: "Cheesecake Caramel",
        description: "Cheesecake maison, coulant caramel beurre salé",
        price: "9",
        badge: null,
        image: "A7400114 18.44.33.jpg",
      },
      {
        name: "Gâteau Chocolat",
        description: "Moelleux au chocolat fait maison, sucre glace",
        price: "5",
        badge: null,
        image: "A7400256.jpg",
        objectPosition: "center 65%",
      },
      {
        name: "Smoothie Bowl",
        description: "Base onctueuse aux fruits, granola, myrtilles, banane & coulis de cerises",
        price: "8",
        badge: null,
        image: "A7403481.jpg",
      },
    ],
  },
  {
    category: "Boissons",
    items: [
      {
        name: "Cloud Pistachio Latte",
        description: "Latte glacé, crème de pistache, lait & crème fouettée",
        price: "7",
        badge: null,
        image: "A7400225.jpg",
      },
      {
        name: "Pink Coco Pitaya",
        description: "Lait de coco, coulis de fruits rouges maison & pitaya",
        price: "7",
        badge: null,
        image: "A7403452.jpg",
      },
      {
        name: "Ube Latte",
        description: "Latte à l'ube (igname violet)",
        price: "7",
        badge: null,
        image: "A7403309.jpg",
        objectPosition: "center top",
      },
      {
        name: "Hojicha Latte",
        description: "Latte au thé hojicha torréfié",
        price: "7",
        badge: null,
        image: null,
      },
      {
        name: "Pink Limonade 86",
        description: "Limonade maison, citron frais & sirop de fruits rouges",
        price: "6",
        badge: null,
        image: "IMG_3338 19.15.09.jpg",
      },
      {
        name: "Iced Coffee",
        description: "Café froid onctueux, servi sur glace",
        price: "6",
        badge: null,
        image: null,
      },
      {
        name: "Peanut Butter Coffee",
        description: "Café onctueux au beurre de cacahuète",
        price: "6",
        badge: null,
        image: null,
      },
      {
        name: "Chocolat Viennois",
        description: "Chocolat chaud & crème fouettée",
        price: "6",
        badge: null,
        image: "A7403410.jpg",
      },
      {
        name: "Tiramisu Coffee",
        description: "Café, crème mascarpone & cacao",
        price: "5,50",
        badge: null,
        image: "IMG_3292.jpg",
      },
      {
        name: "Pistachio Coffee",
        description: "Café à la pistache",
        price: "5,50",
        badge: null,
        image: "A7400219.jpg",
      },
      {
        name: "Limonade maison",
        description: "Limonade fraîche maison",
        price: "4,50",
        badge: null,
        image: null,
      },
    ],
  },
  {
    category: "Matchas",
    items: [
      {
        name: "Matcha Bora Bora",
        description: "Matcha aux notes exotiques",
        price: "8",
        badge: null,
        image: null,
      },
      {
        name: "Matcha Red Velvet",
        description: "Matcha red velvet",
        price: "8",
        badge: null,
        image: "A7400153.jpg",
      },
      {
        name: "Salted Maple Matcha",
        description: "Matcha, sirop d'érable & sel rose d'Himalaya",
        price: "7",
        badge: null,
        image: "A7400245.jpg",
      },
      {
        name: "Matcha Coco Fraise Vanille",
        description: "Matcha, lait de coco, fraise & vanille",
        price: "7",
        badge: null,
        image: null,
      },
      {
        name: "Matcha Limonade",
        description: "Matcha & limonade maison",
        price: "6",
        badge: null,
        image: "A7400239 18.44.34.jpg",
      },
      {
        name: "Matcha Verde",
        description: "Matcha pur, lait froid",
        price: "5,50",
        badge: null,
        image: "A7400205 18.44.33.jpg",
      },
    ],
  },
  {
    category: "Cafés & Thés",
    items: [
      {
        name: "Américano",
        description: "Espresso allongé",
        price: "4,50",
        badge: null,
        image: null,
      },
      {
        name: "Latte Macchiato",
        description: "Espresso, lait chaud mousseux",
        price: "4",
        badge: null,
        image: "IMG_3013 19.14.52.jpg",
      },
      {
        name: "Mocha",
        description: "Espresso, chocolat & lait mousseux",
        price: "4,50",
        badge: null,
        image: null,
      },
      {
        name: "Chocolat chaud",
        description: "Chocolat chaud onctueux",
        price: "4",
        badge: null,
        image: null,
      },
      {
        name: "Cappuccino",
        description: "Espresso & mousse de lait",
        price: "3,50",
        badge: null,
        image: "A7400039.jpg",
        objectPosition: "center 65%",
      },
      {
        name: "Café",
        description: "Café filtre",
        price: "3",
        badge: null,
        image: null,
      },
      {
        name: "Thé à la menthe",
        description: "Thé à la menthe fraîche",
        price: "3,50",
        badge: null,
        image: null,
      },
      {
        name: "Thés spéciaux",
        description: "Sélection de thés du moment",
        price: "3,50",
        badge: null,
        image: null,
      },
      {
        name: "Double Espresso",
        description: "Double shot d'espresso",
        price: "4",
        badge: null,
        image: null,
      },
      {
        name: "Espresso",
        description: "Espresso serré",
        price: "2,50",
        badge: null,
        image: null,
      },
      {
        name: "Softs",
        description: "Coca, Sprite, Fanta…",
        price: "3",
        badge: null,
        image: "A7400143 18.44.33.jpg",
      },
      {
        name: "Eau",
        description: "Eau plate ou pétillante",
        price: "2,50",
        badge: null,
        image: null,
      },
    ],
  },
  {
    category: "Mocktails",
    items: [
      {
        name: "Mocktail Premium",
        description: "Mocktail créatif du moment, frais & sans alcool",
        price: "9",
        badge: null,
        image: "IMG_3358-2.jpg",
      },
      {
        name: "Mojito Classique",
        description: "Menthe fraîche, citron vert, sucre de canne & eau pétillante",
        price: "6",
        badge: null,
        image: "A7403252.jpg",
        objectPosition: "center top",
      },
      {
        name: "Mojito Violette",
        description: "Sirop violette, citron vert & eau pétillante",
        price: "6",
        badge: null,
        image: null,
      },
      {
        name: "Mojito Fruits Rouges",
        description: "Fruits rouges, citron vert & eau pétillante",
        price: "6",
        badge: null,
        image: "A7400210.jpg",
      },
    ],
  },
];
